'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster
    
    '''<summary>
    '''theme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents theme As Global.System.Web.UI.HtmlControls.HtmlLink
    
    '''<summary>
    '''scrpman1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents scrpman1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''AliasSistema control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AliasSistema As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBemVindo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBemVindo As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''_lbl_menu_default control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_default As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_cargas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_cargas As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_oleo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_oleo As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_usuarios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_usuarios As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lbl_menu_veiculos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_menu_veiculos As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_solicitacao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_solicitacao As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_config control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_config As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_relatorios control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_relatorios As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''_lbl_menu_atualizacoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _lbl_menu_atualizacoes As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
