'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Solicitacoes
    
    '''<summary>
    '''btn_filtro_todos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_filtro_todos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_filtro_abertos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_filtro_abertos As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_filtro_finalizadas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_filtro_finalizadas As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lbl_Mensagem_Grid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Mensagem_Grid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''grid_solicitacoes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grid_solicitacoes As Global.System.Web.UI.WebControls.GridView
End Class
