'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IncluirUsuario
    
    '''<summary>
    '''txt_cod_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_cod_usuario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_nome_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nome_usuario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_sobrenome_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_sobrenome_usuario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_login control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_login As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_senha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_senha As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_nascimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nascimento As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''drp_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_status As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''drp_perfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drp_perfil As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_registrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_registrar As Global.System.Web.UI.WebControls.Button
End Class
